
version: '3'
services:
  aihub:
    image: nginx
    restart: unless-stopped
    ports:
      - '8888:8888'
    volumes:
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/deep-learning/default.conf:/etc/nginx/conf.d/default.conf

    
  app1:
    image: ccr.ccs.tencentyun.com/cube-studio/aihub:app1
    restart: unless-stopped
    entrypoint: /src/docker/entrypoint.sh
    command: ["python", "app.py"]
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/deep-learning/app1:/app
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/src:/src
      - /mnt/aihub:/src/cubestudio/aihub/web/static
    environment:
      APPNAME: 'app1'
      REDIS_URL: 'redis://:admin@125.124.48.210:6379/0'
      REQ_TYPE: 'asynchronous'
      NVIDIA_VISIBLE_DEVICES: all
      UPLOAD_DIR: '/src/cubestudio/aihub/web/static/example/app1/upload'
    
    
  animegan:
    image: ccr.ccs.tencentyun.com/cube-studio/aihub:animegan
    restart: unless-stopped
    entrypoint: /src/docker/entrypoint.sh
    command: ["python", "app.py"]
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/deep-learning/animegan:/app
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/src:/src
      - /mnt/aihub:/src/cubestudio/aihub/web/static
    environment:
      APPNAME: 'animegan'
      REDIS_URL: 'redis://:admin@125.124.48.210:6379/0'
      REQ_TYPE: 'asynchronous'
      NVIDIA_VISIBLE_DEVICES: all
      UPLOAD_DIR: '/src/cubestudio/aihub/web/static/example/animegan/upload'
    
    
  stable-diffusion:
    image: ccr.ccs.tencentyun.com/cube-studio/aihub:stable-diffusion
    restart: unless-stopped
    entrypoint: /src/docker/entrypoint.sh
    command: ["python", "app.py"]
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/deep-learning/stable-diffusion:/app
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/src:/src
      - /mnt/aihub:/src/cubestudio/aihub/web/static
    environment:
      APPNAME: 'stable-diffusion'
      REDIS_URL: 'redis://:admin@125.124.48.210:6379/0'
      REQ_TYPE: 'asynchronous'
      NVIDIA_VISIBLE_DEVICES: all
      UPLOAD_DIR: '/src/cubestudio/aihub/web/static/example/stable-diffusion/upload'
    
    
  paddleocr:
    image: ccr.ccs.tencentyun.com/cube-studio/aihub:paddleocr
    restart: unless-stopped
    entrypoint: /src/docker/entrypoint.sh
    command: ["python", "app.py"]
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/deep-learning/paddleocr:/app
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/src:/src
      - /mnt/aihub:/src/cubestudio/aihub/web/static
    environment:
      APPNAME: 'paddleocr'
      REDIS_URL: 'redis://:admin@125.124.48.210:6379/0'
      REQ_TYPE: 'asynchronous'
      NVIDIA_VISIBLE_DEVICES: all
      UPLOAD_DIR: '/src/cubestudio/aihub/web/static/example/paddleocr/upload'
    
    
  gfpgan:
    image: ccr.ccs.tencentyun.com/cube-studio/aihub:gfpgan
    restart: unless-stopped
    entrypoint: /src/docker/entrypoint.sh
    command: ["python", "app.py"]
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/deep-learning/gfpgan:/app
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/src:/src
      - /mnt/aihub:/src/cubestudio/aihub/web/static
    environment:
      APPNAME: 'gfpgan'
      REDIS_URL: 'redis://:admin@125.124.48.210:6379/0'
      REQ_TYPE: 'asynchronous'
      NVIDIA_VISIBLE_DEVICES: all
      UPLOAD_DIR: '/src/cubestudio/aihub/web/static/example/gfpgan/upload'
    
    
  paddlespeech-asr:
    image: ccr.ccs.tencentyun.com/cube-studio/aihub:paddlespeech-asr
    restart: unless-stopped
    entrypoint: /src/docker/entrypoint.sh
    command: ["python", "app.py"]
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/deep-learning/paddlespeech-asr:/app
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/src:/src
      - /mnt/aihub:/src/cubestudio/aihub/web/static
    environment:
      APPNAME: 'paddlespeech-asr'
      REDIS_URL: 'redis://:admin@125.124.48.210:6379/0'
      REQ_TYPE: 'asynchronous'
      NVIDIA_VISIBLE_DEVICES: all
      UPLOAD_DIR: '/src/cubestudio/aihub/web/static/example/paddlespeech-asr/upload'
    
    
  humanseg:
    image: ccr.ccs.tencentyun.com/cube-studio/aihub:humanseg
    restart: unless-stopped
    entrypoint: /src/docker/entrypoint.sh
    command: ["python", "app.py"]
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/deep-learning/humanseg:/app
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/src:/src
      - /mnt/aihub:/src/cubestudio/aihub/web/static
    environment:
      APPNAME: 'humanseg'
      REDIS_URL: 'redis://:admin@125.124.48.210:6379/0'
      REQ_TYPE: 'asynchronous'
      NVIDIA_VISIBLE_DEVICES: all
      UPLOAD_DIR: '/src/cubestudio/aihub/web/static/example/humanseg/upload'
    
    
  paddlespeech-cls:
    image: ccr.ccs.tencentyun.com/cube-studio/aihub:paddlespeech-cls
    restart: unless-stopped
    entrypoint: /src/docker/entrypoint.sh
    command: ["python", "app.py"]
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/deep-learning/paddlespeech-cls:/app
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/src:/src
      - /mnt/aihub:/src/cubestudio/aihub/web/static
    environment:
      APPNAME: 'paddlespeech-cls'
      REDIS_URL: 'redis://:admin@125.124.48.210:6379/0'
      REQ_TYPE: 'asynchronous'
      NVIDIA_VISIBLE_DEVICES: all
      UPLOAD_DIR: '/src/cubestudio/aihub/web/static/example/paddlespeech-cls/upload'
    
    
  ddddocr:
    image: ccr.ccs.tencentyun.com/cube-studio/aihub:ddddocr
    restart: unless-stopped
    entrypoint: /src/docker/entrypoint.sh
    command: ["python", "app.py"]
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/deep-learning/ddddocr:/app
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/src:/src
      - /mnt/aihub:/src/cubestudio/aihub/web/static
    environment:
      APPNAME: 'ddddocr'
      REDIS_URL: 'redis://:admin@125.124.48.210:6379/0'
      REQ_TYPE: 'asynchronous'
      NVIDIA_VISIBLE_DEVICES: all
      UPLOAD_DIR: '/src/cubestudio/aihub/web/static/example/ddddocr/upload'
    
    
  paddlespeech-tts:
    image: ccr.ccs.tencentyun.com/cube-studio/aihub:paddlespeech-tts
    restart: unless-stopped
    entrypoint: /src/docker/entrypoint.sh
    command: ["python", "app.py"]
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/deep-learning/paddlespeech-tts:/app
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/src:/src
      - /mnt/aihub:/src/cubestudio/aihub/web/static
    environment:
      APPNAME: 'paddlespeech-tts'
      REDIS_URL: 'redis://:admin@125.124.48.210:6379/0'
      REQ_TYPE: 'asynchronous'
      NVIDIA_VISIBLE_DEVICES: all
      UPLOAD_DIR: '/src/cubestudio/aihub/web/static/example/paddlespeech-tts/upload'
    
    
  yolov3:
    image: ccr.ccs.tencentyun.com/cube-studio/aihub:yolov3
    restart: unless-stopped
    entrypoint: /src/docker/entrypoint.sh
    command: ["python", "app.py"]
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/deep-learning/yolov3:/app
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/src:/src
      - /mnt/aihub:/src/cubestudio/aihub/web/static
    environment:
      APPNAME: 'yolov3'
      REDIS_URL: 'redis://:admin@125.124.48.210:6379/0'
      REQ_TYPE: 'asynchronous'
      NVIDIA_VISIBLE_DEVICES: all
      UPLOAD_DIR: '/src/cubestudio/aihub/web/static/example/yolov3/upload'
    
    
  deoldify:
    image: ccr.ccs.tencentyun.com/cube-studio/aihub:deoldify
    restart: unless-stopped
    entrypoint: /src/docker/entrypoint.sh
    command: ["python", "app.py"]
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/deep-learning/deoldify:/app
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/src:/src
      - /mnt/aihub:/src/cubestudio/aihub/web/static
    environment:
      APPNAME: 'deoldify'
      REDIS_URL: 'redis://:admin@125.124.48.210:6379/0'
      REQ_TYPE: 'asynchronous'
      NVIDIA_VISIBLE_DEVICES: all
      UPLOAD_DIR: '/src/cubestudio/aihub/web/static/example/deoldify/upload'
    
    
  panoptic:
    image: ccr.ccs.tencentyun.com/cube-studio/aihub:panoptic
    restart: unless-stopped
    entrypoint: /src/docker/entrypoint.sh
    command: ["python", "app.py"]
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/deep-learning/panoptic:/app
      - /data/k8s/kubeflow/pipeline/workspace/pengluan/cube-studio/aihub/src:/src
      - /mnt/aihub:/src/cubestudio/aihub/web/static
    environment:
      APPNAME: 'panoptic'
      REDIS_URL: 'redis://:admin@125.124.48.210:6379/0'
      REQ_TYPE: 'asynchronous'
      NVIDIA_VISIBLE_DEVICES: all
      UPLOAD_DIR: '/src/cubestudio/aihub/web/static/example/panoptic/upload'
    
    